import Head from "next/head"
import { Container } from "@mui/material"
import { api } from "@/api/axios"
import { Author, Book } from "@/api/types"
import Layout from "@/components/layout"
import Banner from "@/components/pages/index/Banner"
import PopularCategories from "@/components/pages/index/popularCategories"
import Top from "@/components/pages/index/top"

export async function getServerSideProps() {
  const { data: books } = await api.get("/books")
  const { data: authors } = await api.get("/authors")

  return { props: { books, authors } }
}

interface HomeProps {
  books: Book[]
  authors: Author[]
}

export default function Home({ books, authors }: HomeProps) {
  return (
    <>
      <Head>
        <title>Storybook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Container>
          <Banner />
          <PopularCategories />
          <Top books={books} authors={authors} />
        </Container>
      </Layout>
    </>
  )
}
